### ISSUE TITLE
Corrected in v0.28.3

### ISSUE THREAD

**Issue by fountainhead** [frankhale/electron-webview-ipc-test#1]
@frankhale this demo is proving very useful for me to understand how electron works. Thank you.
This now seems to work in v0.28.3. Correct?

What does this part of the code do? Or how is it intended to be used?

```js
  wv.addEventListener('ipc-message', function(e) {
    console.log(e.channel);
  }.bind(this));
```

Sorry for the basic questions :-)

**Comment by frankhale** [comment]
Yeah this little demo was made up to demonstrate some issues for using IPC that was happening with a few versions of Electron. Basically if you changed the source of a webview any IPC you were doing with your webview and your main process would die. This should work fine in 0.28.2 and 3 as the problems were resolved. 

The lines of code you are referencing are just listening for an IPC message and then logging whatever is on the IPC channel to the dev tools window. I was using this to make sure that IPC was working correctly after the source had changed in the webview. The log messages would just keep logging any IPC data received to the dev tools console forever.

**Comment by frankhale** [comment]
This issue I was speaking of was actually fixed in 0.27.3. 

https://github.com/atom/electron/releases/tag/v0.27.3

**Comment by fountainhead** [comment]
Thank you. Actually, I tried commenting that code and it does not seem to make any difference.
Hence, I am wondering what it was meant to do and the use-case when its useful.

I couldn't find any good documentation of `channel` to understand it.

**Comment by frankhale** [comment]
Here is the docs for IPC:

main process:

https://github.com/atom/electron/blob/master/docs/api/ipc-main-process.md

renderer (aka Browser Window)

https://github.com/atom/electron/blob/master/docs/api/ipc-renderer.md

In this case of this example I am using the webviews IPC API:

https://github.com/atom/electron/blob/master/docs/api/web-view-tag.md#ipc-message

Basically you have a browser window or a webview send IPC messages back to the main process and the main process catches them. This is so you can communicate across the various processes in a coherent way.

**Comment by fountainhead** [comment]
Thank you! :-)
